[config]
default_to_workspace = false
skip_core_tasks = true

[tasks.lint]
script = '''
#!@duckscript

exec cargo check --all-targets --all-features
exec cargo clippy --all-targets --all-features -- -D warnings
'''

[tasks.dev]
script = '''
#!@duckscript

exec cargo build --target wasm32-unknown-unknown --package _client --release
exec wasm-bindgen --out-dir ./target/wasm32-html --out-name client --target no-modules --no-typescript --no-modules-global wasm_vendor_entry ./target/wasm32-unknown-unknown/release/_client.wasm

set_env PORT 8080
set_env JWT_SECRET "ciallo@0721"
exec cargo run --package _server
'''

[tasks.watch]
watch = { watch = ["./packages/"] }
run_task = { name = ["dev"], fork = true }

[tasks.run]
script = '''
#!@duckscript

exec docker build -t ciallo-0721 .
exec docker run -d -p 8080:80 -v 0721-cache:/home/cache -e JWT_SECRET=ciallo@0721 --restart=always ciallo-0721:latest
'''

[tasks.clean]
script = '''
#!@duckscript

exec cargo clean
'''
