[package]
name = "_database"
version.workspace = true
edition.workspace = true

[dependencies]
_types = { path = "../types" }
_functions = { path = "../functions" }

tairitsu-database = { workspace = true }

anyhow = { workspace = true }
async-trait = { workspace = true }
derive_more = { workspace = true }
once_cell = { workspace = true }
cfg-if = { workspace = true }

base64 = { workspace = true }
bytes = { workspace = true }
chrono = { workspace = true }
futures = { workspace = true }

serde = { workspace = true }
serde_json = { workspace = true }
toml = { workspace = true }
strum = { workspace = true }
uuid = { workspace = true }
log = { workspace = true }

tokio = { version = "^1", features = ["full"] }
tracing = { workspace = true }

worker = { workspace = true }
sea-orm = { workspace = true }

jsonwebtoken = "^9"
bcrypt = "^0.16"
sha3 = "^0.10"

image = { workspace = true }
webp = { workspace = true }
webp-animation = { workspace = true }

[features]
cloudflare = ["tairitsu-database/cloudflare"]
native = ["tairitsu-database/native"]
wasi = ["tairitsu-database/wasi"]
