[header]
welcome = "Willkommen, "
loading = "Laden..."

portal = "Portal"
images = "Bilder"
users = "Benutzer"

login = "Anmelden"
logout = "Abmelden"
register = "Registrieren"

username = "Benutzername"
password = "Passwort"
email = "E-Mail"

[portal]
upload = "Hochladen"
progress = "Fortschritt"
download = "Herunterladen"
delete = "Löschen"
