[header]
welcome = "Willkommen, "
loading = "Laden..."

portal = "Portal"
images = "Bilder"
users = "Benutzer"
config = "Konfiguration"

login = "Anmelden"
logout = "Abmelden"
register = "Registrieren"

username = "Benutzername"
password = "Passwort"
email = "E-Mail"

[portal]
upload = "Hochladen"
download = "Herunterladen"
delete = "Löschen"

progress = "Fortschritt"
fail = "Fehler"
