[header]
welcome = "Willkommen, "
loading = "Laden..."

portal = "Portal"
images = "Bilder"
users = "Benutzer"
config = "Konfiguration"

login = "Anmelden"
logout = "Abmelden"
register = "Registrieren"

username = "Benutzername"
password = "Passwort"
email = "E-Mail"

user = "Benutzer"
manager = "Manager"

[portal]
upload = "Hochladen"
download = "Herunterladen"
delete = "Löschen"

progress = "Fortschritt"
fail = "Fehler"

[images]
total-count = "Gesamtzahl"
load-more = "Mehr laden"

[config.portal]
title-suffix = "Seitentitel"
footer-banner = "Fußzeilentext"
language = "Bevorzugte Sprache"
timezone = "Zeitzone"

[config.router]
media-entry-path = "Medien-Routeneinstieg"
limit-referrer-host = "Referrer-Host-Whitelist"

[config.upload]
image-size-limit = "Bildgrößenbeschränkung"
webp-auto-convert = "Automatische Konvertierung in WebP-Format"
use-source-file-name = "Verwenden Sie den Quelldateinamen"
