[header]
welcome = "Welcome, "
loading = "Loading"

portal = "Portal"
images = "Images"
users = "Users"
config = "Config"

login = "Login"
logout = "Logout"
register = "Register"

username = "Username"
password = "Password"
email = "Email"

[portal]
upload = "Upload"
download = "Download"
delete = "Delete"

progress = "Progress"
fail = "Fail"
