[header]
welcome = "Welcome, "
loading = "Loading"

portal = "Portal"
images = "Images"
users = "Users"
config = "Config"

login = "Login"
logout = "Logout"
register = "Register"

username = "Username"
password = "Password"
email = "Email"

user = "User"
manager = "Manager"

[portal]
upload = "Upload"
download = "Download"
delete = "Delete"

progress = "Progress"
fail = "Fail"

[images]
total-count = "Total Count"
load-more = "Load More"

[config.portal]
engine-version = "Engine Version"
title-suffix = "Site Title"
footer-banner = "Footer Banner"
language = "Preferred Language"
timezone = "Timezone"

[config.router]
media-entry-path = "Media Entry Path"
limit-referrer-host = "Limit Referrer Host"

[config.upload]
image-size-limit = "Image Size Limit"
webp-auto-convert = "Auto Convert to WebP"
use-source-file-name = "Use Source File Name"
