[header]
welcome = "Bienvenue, "
loading = "Chargement"

images = "Images"
users = "Utilisateurs"

login = "Connexion"
logout = "Déconnexion"
register = "Inscription"

username = "Nom d'utilisateur"
password = "Mot de passe"
email = "Courriel"

[portal]
upload = "Téléverser"
download = "Télécharger"
delete = "Supprimer"
