[header]
welcome = "Bienvenue, "
loading = "Chargement"

portal = "Portail"
images = "Images"
users = "Utilisateurs"
config = "Configuration"

login = "Connexion"
logout = "Déconnexion"
register = "Inscription"

username = "Nom d'utilisateur"
password = "Mot de passe"
email = "Courriel"

user = "Utilisateur"
manager = "Gestionnaire"

[portal]
upload = "Téléverser"
download = "Télécharger"
delete = "Supprimer"

progress = "Progression"
fail = "Échec"

[images]
total-count = "Nombre total"
load-more = "Charger plus"

[config.portal]
title-suffix = "Titre du site"
footer-banner = "Texte du pied de page"
language = "Langue préférée"
timezone = "Fuseau horaire"

[config.router]
media-entry-path = "Entrée du routeur multimédia"
limit-referrer-host = "Liste blanche des noms de domaine de référence"

[config.upload]
image-size-limit = "limite de taille d'image"
webp-auto-convert = "Convertir automatiquement en format WebP"
use-source-file-name = "Utiliser le nom de fichier source"
