[header]
welcome = "Bienvenue, "
loading = "Chargement"

portal = "Portail"
images = "Images"
users = "Utilisateurs"
config = "Configuration"

login = "Connexion"
logout = "Déconnexion"
register = "Inscription"

username = "Nom d'utilisateur"
password = "Mot de passe"
email = "Courriel"

[portal]
upload = "Téléverser"
download = "Télécharger"
delete = "Supprimer"

progress = "Progression"
fail = "Échec"
