[header]
welcome = "Benvenuto,"
loading = "Caricamento..."

portal = "Portale"
images = "Immagini"
users = "Utenti"

login = "Accesso"
logout = "Disconnettersi"
register = "Registrati"

username = "Nome utente"
password = "Parola d'ordine"
email = "E-mail"

[portal]
upload = "Carica"
download = "Scarica"
delete = "Elimina"
