[header]
welcome = "ようこそ、"
loading = "読み込み中"

portal = "ポータル"
images = "画像"
users = "ユーザー"
config = "設定"

login = "ログイン"
logout = "ログアウト"
register = "登録"

username = "ユーザー名"
password = "パスワード"
email = "メールアドレス"

user = "ユーザー"
manager = "マネージャー"

[portal]
upload = "アップロード"
download = "ダウンロード"
delete = "削除"

progress = "進行中"
fail = "失敗"

[images]
total-count = "合計数"
load-more = "さらに読み込む"

[config.portal]
title-suffix = "サイトタイトル"
footer-banner = "フッターバナー"
language = "言語"
timezone = "タイムゾーン"

[config.router]
media-entry-path = "メディアルーターエントリ"
limit-referrer-host = "リファラーホストのホワイトリスト"

[config.upload]
image-size-limit = "画像サイズ制限"
webp-auto-convert = "WebP形式に自動変換するかどうか"
use-source-file-name = "元のファイル名を使用するかどうか"
