[header]
welcome = "ようこそ、"
loading = "読み込み中"

images = "画像"
users = "ユーザー"

login = "ログイン"
logout = "ログアウト"
register = "登録"

username = "ユーザー名"
password = "パスワード"
email = "メールアドレス"

[portal]
upload = "アップロード"
download = "ダウンロード"
delete = "削除"
