[header]
welcome = "Добро пожаловать, "
loading = "Загрузка..."

portal = "Портал"
images = "Изображения"
users = "Пользователи"

login = "Войти"
logout = "Выйти"
register = "Регистрация"

username = "Имя пользователя"
password = "Пароль"
email = "Электронная почта"

[portal]
upload = "Загрузить"
progress = "Прогресс"
download = "Скачать"
delete = "Удалить"
