[header]
welcome = "欢迎，"
loading = "加载中"

portal = "门户"
images = "图片"
users = "用户"

login = "登录"
logout = "退出"
register = "注册"

username = "用户名"
password = "密码"
email = "邮箱"

[portal]
upload = "上传"
download = "下载"
delete = "删除"
