[header]
welcome = "歡迎，"
loading = "加載中"

portal = "門戶"
images = "圖片"
users = "用戶"

login = "登錄"
logout = "登出"

username = "用戶名"
password = "密碼"
email = "郵箱"

[portal]
upload = "上傳"
download = "下載"
delete = "刪除"
