[header]
welcome = "歡迎，"
loading = "加載中"

portal = "門戶"
images = "圖片"
users = "用戶"
config = "配置"

login = "登錄"
logout = "登出"
register = "註冊"

username = "用戶名"
password = "密碼"
email = "郵箱"

[portal]
upload = "上傳"
download = "下載"
delete = "刪除"

progress = "進度"
fail = "失敗"
