[package]
name = "_server"
version.workspace = true
edition.workspace = true

[dependencies]
_client = { path = "../client" }
_database = { path = "../database" }
_types = { path = "../types" }

hikari-boot = { workspace = true }

anyhow = { workspace = true }
async-trait = { workspace = true }
derive_more = { workspace = true }
once_cell = { workspace = true }
cfg-if = { workspace = true }

base64 = { workspace = true }
bytes = { workspace = true }
chrono = { workspace = true }
futures = { workspace = true }
tokio = { version = "^1", features = ["full"] }

serde = { workspace = true }
serde_json = { workspace = true }
toml = { workspace = true }
strum = { workspace = true }
uuid = { workspace = true }

log = { workspace = true }
tracing = { workspace = true }
tracing-subscriber = { workspace = true }
tracing-appender = { workspace = true }

image = { workspace = true }
webp = { workspace = true }

axum = { version = "^0.8", features = ["query", "multipart"] }
axum-extra = { version = "^0.10", features = [
  "typed-header",
  "multipart",
  "cookie",
] }
clap = { version = "^4", features = ["derive"] }
hyper = { version = "^1", features = ["server", "http1"] }
tower = { version = "^0.5", features = ["make"] }
tower-http = { version = "^0.6", features = [
  "fs",
  "trace",
  "compression-gzip",
] }
url = "^2"

stylist = { version = "^0.13", features = [
  "yew_integration",
  "ssr",
  "hydration",
] }
yew = { version = "^0.21", features = ["ssr", "hydration"] }

[features]
default = ["native"]
cloudflare = ["_database/cloudflare"]
native = ["_database/native"]
wasi = ["_database/wasi"]
